/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author User
 */
public class frmProveedor extends javax.swing.JFrame {

    /**
     * Creates new form frmProveedor
     */
    public frmProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        tlBuscar = new javax.swing.JButton();
        tlInsertar = new javax.swing.JButton();
        tlEditar = new javax.swing.JButton();
        tlEliminar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtDescri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnAñadePro = new javax.swing.JButton();
        btnEliminaPro = new javax.swing.JButton();
        btnEditaPro = new javax.swing.JButton();
        txtBuscarPro = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnBuscarPro = new javax.swing.JButton();
        actualizaTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        tablaProveedor.setBackground(new java.awt.Color(51, 51, 51));
        tablaProveedor.setForeground(new java.awt.Color(204, 204, 204));
        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProveedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jToolBar1.setBackground(new java.awt.Color(51, 51, 51));
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        tlBuscar.setBackground(new java.awt.Color(51, 51, 51));
        tlBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscando.png"))); // NOI18N
        tlBuscar.setBorderPainted(false);
        tlBuscar.setFocusPainted(false);
        tlBuscar.setFocusable(false);
        tlBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlBuscar.setMaximumSize(new java.awt.Dimension(50, 50));
        tlBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(tlBuscar);

        tlInsertar.setBackground(new java.awt.Color(51, 51, 51));
        tlInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insert.png"))); // NOI18N
        tlInsertar.setBorderPainted(false);
        tlInsertar.setFocusPainted(false);
        tlInsertar.setFocusable(false);
        tlInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlInsertar.setMaximumSize(new java.awt.Dimension(50, 50));
        tlInsertar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlInsertarActionPerformed(evt);
            }
        });
        jToolBar1.add(tlInsertar);

        tlEditar.setBackground(new java.awt.Color(51, 51, 51));
        tlEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        tlEditar.setBorderPainted(false);
        tlEditar.setFocusPainted(false);
        tlEditar.setFocusable(false);
        tlEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlEditar.setMaximumSize(new java.awt.Dimension(50, 50));
        tlEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(tlEditar);

        tlEliminar.setBackground(new java.awt.Color(51, 51, 51));
        tlEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        tlEliminar.setBorderPainted(false);
        tlEliminar.setFocusPainted(false);
        tlEliminar.setFocusable(false);
        tlEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlEliminar.setMaximumSize(new java.awt.Dimension(50, 50));
        tlEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(tlEliminar);

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/info.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(null);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nombre");

        jSeparator7.setBackground(new java.awt.Color(102, 153, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Añadir proveedores");

        txtDescri.setBackground(new java.awt.Color(102, 102, 102));
        txtDescri.setForeground(new java.awt.Color(204, 204, 204));
        txtDescri.setBorder(null);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Descripción");

        jSeparator8.setBackground(new java.awt.Color(102, 153, 255));

        btnAñadePro.setBackground(new java.awt.Color(153, 255, 153));
        btnAñadePro.setForeground(new java.awt.Color(51, 51, 51));
        btnAñadePro.setText("Añadir proveedor");
        btnAñadePro.setBorder(null);
        btnAñadePro.setBorderPainted(false);
        btnAñadePro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadePro.setFocusPainted(false);
        btnAñadePro.setFocusable(false);

        btnEliminaPro.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminaPro.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminaPro.setText("Eliminar proveedor");
        btnEliminaPro.setBorder(null);
        btnEliminaPro.setBorderPainted(false);
        btnEliminaPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminaPro.setFocusPainted(false);
        btnEliminaPro.setFocusable(false);

        btnEditaPro.setBackground(new java.awt.Color(51, 102, 255));
        btnEditaPro.setForeground(new java.awt.Color(51, 51, 51));
        btnEditaPro.setText("Editar  proveedor");
        btnEditaPro.setBorder(null);
        btnEditaPro.setBorderPainted(false);
        btnEditaPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditaPro.setFocusPainted(false);
        btnEditaPro.setFocusable(false);

        txtBuscarPro.setBackground(new java.awt.Color(102, 102, 102));
        txtBuscarPro.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarPro.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        btnBuscarPro.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarPro.setBorder(null);
        btnBuscarPro.setBorderPainted(false);
        btnBuscarPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPro.setFocusPainted(false);
        btnBuscarPro.setFocusable(false);

        actualizaTabla.setBackground(new java.awt.Color(51, 51, 51));
        actualizaTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        actualizaTabla.setBorderPainted(false);
        actualizaTabla.setFocusPainted(false);
        actualizaTabla.setFocusable(false);
        actualizaTabla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizaTabla.setMaximumSize(new java.awt.Dimension(50, 50));
        actualizaTabla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actualizaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtBuscarPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(actualizaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(jSeparator7)
                            .addComponent(txtDescri)
                            .addComponent(jSeparator8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAñadePro, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminaPro, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditaPro, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(actualizaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescri, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadePro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlBuscarActionPerformed

    private void tlInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlInsertarActionPerformed

    private void tlEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlEditarActionPerformed

    private void tlEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlEliminarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void actualizaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizaTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizaTabla;
    public javax.swing.JButton btnAñadePro;
    public javax.swing.JButton btnBuscarPro;
    public javax.swing.JButton btnEditaPro;
    public javax.swing.JButton btnEliminaPro;
    public javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable tablaProveedor;
    public javax.swing.JButton tlBuscar;
    public javax.swing.JButton tlEditar;
    public javax.swing.JButton tlEliminar;
    public javax.swing.JButton tlInsertar;
    public javax.swing.JTextField txtBuscarPro;
    public javax.swing.JTextField txtDescri;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
